### ISSUE TITLE
BUG - Dividir em blocos randômicos

### ISSUE THREAD

**Issue by edmundo-vitor** [lmajowka/btc-finder#10]
Olá pessoal, venho compartilhar com vocês um bug que acabei encontrando recentemente:

![image](https://github.com/lmajowka/btc-finder/assets/58776991/11dccfb1-c270-44c4-b86a-b1baccf920f1)

Ao executar na opção de dividir em blocos randômicos acabei me deparando com esse erro após um tempo de execução.
No meu caso deu esse erro 2x na mesma quantidade de chaves buscadas (16M).

Acredito que se for guardar as keys para validar quantas já foram buscadas, acho que vai ter que persistir em um arquivo, tendo em vista essa limitação de tipo na memória. Chega um momento que ta batendo 100% de uso da memória RAM, é muita chave para deixar em memória.

**Comment by rafinhahdc19** [comment]
ja enviei um pull request para solucionar esse erro apenas esperar ser aceito
